n = input('Digite algo: ')
print(f'O tipo primitivo é: {type(n)}')
print(f'Ta em maiúsculo: {n.isupper()}')
print(f'ta em minusculo: {n.islower()}')
print(f'É um número: {n.isnumeric()}')
print(f'É alfabetico: {n.isalpha()}')
print(f'So tem espaços: {n.isspace()}')
print(f'Está capitalizada: {n.istitle()}')
print(f'É um alfanumerico: {n.isalnum()}')
